name: Setup base env action

description: Setup base env

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v6
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org

    - name: Install @antfu/ni globally
      shell: bash
      run: |
        npm i -g @antfu/ni
        echo "NI_DEFAULT_AGENT=pnpm" >> $GITHUB_ENV
        echo "NI_CATALOG=true" >> $GITHUB_ENV
        echo "NI_AUTO_INSTALL=true" >> $GITHUB_ENV
