name: lvr release

on:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/pnpm-ni.yml
    with:
      run_script: nlx lvr release
    secrets: inherit
