name: Publish

on:
  workflow_call:
    inputs:
      sync_cnpm:
        required: false
        type: boolean

jobs:
  publish:
    uses: ./.github/workflows/pnpm-ni.yml
    with:
      run_script: nlx lvr publish${{ inputs.sync_cnpm == true && ' --sync-cnpm' || ''}}
    secrets: inherit
